Add post "Rails - Why pure string condition is not safe?".
nustechnology/technical-notes pull request #1
Opened 2017-04-24 14:37 UTC by minhnhanlk

Description: If you're a Rails guy, you always hear that you should not use **pure string condition** because it is not safe. Do you ever wonder why it's not safe? If not, take a few minutes to read this post and you will understand.

Image: https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/09/1473921124injection-attack.jpg

2017-04-25 02:52 UTC, namtvz requested changes

2017-04-25 02:52 UTC, namtvit07 commented on rails-why-pure-string-condition-is-not-safe.md
> +Especially if you're a NUSer, at the first days you got familiar with Rails your trainer always told you that you shouldn't use **pure string conditions** when building a sql query. But I'm sure that
But I'm sure that your trainer did not told you why we shouldn't use it in details, right?
--> should be changed to something similar to "But your trainer might not tell you why we shouldn't use it in details"

2017-04-25 02:52 UTC, namtvit07 commented on rails-why-pure-string-condition-is-not-safe.md
> +To clarify what I said above, I'll give you some examples to show you how hacker ca make you hurt easily! And I also tell you how to keep your code safe in these examples.
ca make --> can make

2017-04-25 02:52 UTC, namtvit07 commented on rails-why-pure-string-condition-is-not-safe.md
> +**To be be safe, never pass user input directly to delete_all method.**
Duplicated "be"

2017-04-25 02:52 UTC, namtvit07 commented on rails-why-pure-string-condition-is-not-safe.md
> +**To be be safe, always convert user’s input to a string or integer if using it as the primary key in `exists?`**
Duplicated "be"

2017-04-25 03:07 UTC, namtvz approved these changes

2017-04-25 03:08 UTC, merged

2017-04-27 03:40 UTC, namtvit07 commented on rails-why-pure-string-condition-is-not-safe.md
> +To clarify what I said above, I'll give you some examples to show you how hacker can make you hurt easily! And I also tell you how to keep your code safe in these examples.
Test, ignore it please